# Default values for fastapi-gitops-starter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  tag: "v0.3"

registry:
  createImagePullSecret: true
  secretName: image-pull-secret #pragma: allowlist secret
  server: ghcr.io
  token: "<YOUR_GITHUB_PAT>"

imagePullSecrets:
  - name: image-pull-secret #pragma: allowlist secret

ingress:
  enabled: true
  hosts:
    - host: naavre-dev.minikube.test
      paths:
        - path: /GitOps-Starter
          pathType: Prefix

# Application configuration
app:
  rootPath: "/GitOps-Starter"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 10
